version: "3"
services:
  postgres:
    networks:
        - postgres-network
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
  pgadmin4:
    networks:
        - postgres-network
    image: dpage/pgadmin4
    depends_on:
        - postgres
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin_local@compasso.com.br
      - PGADMIN_DEFAULT_PASSWORD=postgres
    links:
      - "postgres:database"

  app:
    container_name: api-svc
    build: .
    ports:
        - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todo
      KEY: kdlfnsdlnfçskfnmsçfwkefnmlwk
      PORT: 3000
    entrypoint:
      - npm
      - run
      - start:prod
    links:
      - postgres:database
    depends_on:
      - postgres
    networks:
      - postgres-network
volumes:
  reserved: 

networks:
    postgres-network:
       driver: bridge